<a href="https://colab.research.google.com/github/tushhk-ai/NLP/blob/main/Custom_Word_Embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
import tensorflow as tf

print(tf.__version__)

2.11.0


In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sentences=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [4]:
sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size= 500

#### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sentences] 
print(onehot_repr)

[[410, 208, 415, 324], [410, 208, 415, 486], [410, 383, 415, 150], [260, 129, 415, 294, 40], [260, 129, 415, 294, 475], [396, 410, 97, 415, 286], [48, 184, 195, 294]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 410 208 415 324]
 [  0   0   0   0 410 208 415 486]
 [  0   0   0   0 410 383 415 150]
 [  0   0   0 260 129 415 294  40]
 [  0   0   0 260 129 415 294 475]
 [  0   0   0 396 410  97 415 286]
 [  0   0   0   0  48 184 195 294]]


In [10]:
## 10 feature dimesnions
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 410, 208, 415, 324], dtype=int32)

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 227ms/step


array([[ 0.02610001,  0.00682188,  0.02367533,  0.04931192,  0.03671641,
         0.01873559,  0.03058647,  0.01802571,  0.01166396,  0.02880393],
       [ 0.02610001,  0.00682188,  0.02367533,  0.04931192,  0.03671641,
         0.01873559,  0.03058647,  0.01802571,  0.01166396,  0.02880393],
       [ 0.02610001,  0.00682188,  0.02367533,  0.04931192,  0.03671641,
         0.01873559,  0.03058647,  0.01802571,  0.01166396,  0.02880393],
       [ 0.02610001,  0.00682188,  0.02367533,  0.04931192,  0.03671641,
         0.01873559,  0.03058647,  0.01802571,  0.01166396,  0.02880393],
       [-0.03901452,  0.00683612, -0.03060758, -0.02994253,  0.0491318 ,
        -0.0370185 , -0.03644439,  0.02018053, -0.03461653,  0.0256902 ],
       [-0.02158824, -0.01020088,  0.02548417,  0.01939799, -0.02454438,
         0.01840093, -0.02316254,  0.03886975,  0.01566663,  0.01871436],
       [-0.03942998, -0.03465822, -0.02440338,  0.03087249, -0.03737633,
        -0.02090933,  0.0176853 , -0.00049819

In [15]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 36ms/step
[[[ 0.02610001  0.00682188  0.02367533  0.04931192  0.03671641
    0.01873559  0.03058647  0.01802571  0.01166396  0.02880393]
  [ 0.02610001  0.00682188  0.02367533  0.04931192  0.03671641
    0.01873559  0.03058647  0.01802571  0.01166396  0.02880393]
  [ 0.02610001  0.00682188  0.02367533  0.04931192  0.03671641
    0.01873559  0.03058647  0.01802571  0.01166396  0.02880393]
  [ 0.02610001  0.00682188  0.02367533  0.04931192  0.03671641
    0.01873559  0.03058647  0.01802571  0.01166396  0.02880393]
  [-0.03901452  0.00683612 -0.03060758 -0.02994253  0.0491318
   -0.0370185  -0.03644439  0.02018053 -0.03461653  0.0256902 ]
  [-0.02158824 -0.01020088  0.02548417  0.01939799 -0.02454438
    0.01840093 -0.02316254  0.03886975  0.01566663  0.01871436]
  [-0.03942998 -0.03465822 -0.02440338  0.03087249 -0.03737633
   -0.02090933  0.0176853  -0.00049819 -0.02333199  0.01304015]
  [-0.04731597  0.03248397 -0.02968774  0.01212722 -0.046850

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 6654,  998, 8966, 1609])

In [ ]:
print(model.predict(embedded_docs)[0])

[[-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.00425554 -0.00159295 -0.04714153  0.04425247 -0.00973954 -0.04325813
   0.04007108 -0.0143286  -0.03659749 -0.02379028]
 [-0.03786323 -0.02628061  0.02974111 -0.03307171  0.0271405   0.00945134
   0.02378127  0.04176904  0.00514941  0.0152082 ]
 [ 0.04834186  0.04388311 -0.02802253 -0.01475487 -0.01212303  0.03762435
  -0.01166249 -0.02141088  0.04654533  0.01537322]
 [ 0.03276015 -0.00637691  0.03907344 -0.01912468  0.02177186 -0.04630325
   0.00800942 -0.03115667 -0.00486455 -0.04843524]
 [-0.04173617  0.03438064  0.02880521 -0.01896455  0.0323303  -0.00109453
  -0.01675171 -0.00941917 -0.03309294 -0.04779492]]